require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - sevencop

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - expect_correction
      - expect_no_offenses
      - expect_offense

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    RSpecDescribeHttpEndpoint: rspec_describe_http_endpoint
    RSpecExamplesInSameGroup: rspec_examples_in_same_group

RSpec/MultipleExpectations:
  Enabled: false

Sevencop/AutoloadOrdered:
  Enabled: true

Sevencop/HashElementOrdered:
  Enabled: true

Sevencop/MethodDefinitionArgumentsMultiline:
  Enabled: true

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Enabled: true

Sevencop/MethodDefinitionOrdered:
  Enabled: true

Sevencop/RequireOrdered:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
