AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
 Exclude:
   - lib/sevencop.rb

Style/Documentation:
  Enabled: false
