require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - ./lib/sevencop

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - def_node_matcher
    - def_node_search

Metrics:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - expect_correction
      - expect_no_offenses
      - expect_offense

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    RSpecDescribeHttpEndpoint: rspec_describe_http_endpoint
    RSpecEmptyLineAfterLet: rspec_empty_line_after_let
    RSpecExamplesInSameGroup: rspec_examples_in_same_group
    RSpecMatcherConsistentParentheses: rspec_matcher_consistent_parentheses
    RSpecMemoizedHelperBlockDelimiter: rspec_memoized_helper_block_delimiter
    RSpecRailsHaveHttpStatus: rspec_rails_have_http_status
    RSpecRailsStatusCodeCheckBySubject: rspec_rails_status_code_check_by_subject

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    RSpecDescribeHttpEndpoint: rspec_describe_http_endpoint
    RSpecEmptyLineAfterLet: rspec_empty_line_after_let
    RSpecExamplesInSameGroup: rspec_examples_in_same_group
    RSpecMatcherConsistentParentheses: rspec_matcher_consistent_parentheses
    RSpecMemoizedHelperBlockDelimiter: rspec_memoized_helper_block_delimiter
    RSpecRailsHaveHttpStatus: rspec_rails_have_http_status
    RSpecRailsStatusCodeCheckBySubject: rspec_rails_status_code_check_by_subject

Sevencop/AutoloadOrdered:
  Enabled: true

Sevencop/HashElementOrdered:
  Enabled: true

Sevencop/MethodDefinitionArgumentsMultiline:
  Enabled: true

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Enabled: true

Sevencop/MethodDefinitionOrdered:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RequireOrder:
  Enabled: true
