# frozen_string_literal: true

require_relative 'sevencop/cop_concerns'
require_relative 'sevencop/rubocop_extension'
require_relative 'sevencop/version'

require_relative 'rubocop/cop/sevencop/autoload_ordered'
require_relative 'rubocop/cop/sevencop/hash_element_ordered'
require_relative 'rubocop/cop/sevencop/map_method_chain'
require_relative 'rubocop/cop/sevencop/method_definition_arguments_multiline'
require_relative 'rubocop/cop/sevencop/method_definition_in_included'
require_relative 'rubocop/cop/sevencop/method_definition_keyword_argument_ordered'
require_relative 'rubocop/cop/sevencop/method_definition_ordered'
require_relative 'rubocop/cop/sevencop/rails_belongs_to_optional'
require_relative 'rubocop/cop/sevencop/rails_date_and_time_calculation'
require_relative 'rubocop/cop/sevencop/rails_order_field_arel_sql'
require_relative 'rubocop/cop/sevencop/rails_order_field_in_order_of'
require_relative 'rubocop/cop/sevencop/rails_route_as'
require_relative 'rubocop/cop/sevencop/rails_route_ordered'
require_relative 'rubocop/cop/sevencop/rails_specific_action_name'
require_relative 'rubocop/cop/sevencop/rails_uniqueness_validator_explicit_case_sensitivity'
require_relative 'rubocop/cop/sevencop/rails_where_not'
require_relative 'rubocop/cop/sevencop/rspec_describe_http_endpoint'
require_relative 'rubocop/cop/sevencop/rspec_empty_line_after_let'
require_relative 'rubocop/cop/sevencop/rspec_examples_in_same_group'
require_relative 'rubocop/cop/sevencop/rspec_matcher_consistent_parentheses'
require_relative 'rubocop/cop/sevencop/rspec_memoized_helper_block_delimiter'
require_relative 'rubocop/cop/sevencop/rspec_pending_only_example_group'
require_relative 'rubocop/cop/sevencop/rspec_rails_have_http_status'
require_relative 'rubocop/cop/sevencop/rspec_rails_status_code_check_by_subject'
