Sevencop/AutoloadOrdered:
  Description: |
    Sort `autoload` in alphabetical order.
  Enabled: false
  Safe: false

Sevencop/HashElementOrdered:
  Description: |
    Sort Hash elements by key.
  Enabled: false
  Safe: false

Sevencop/MapMethodChain:
  Description: |
    Checks if the map method is used in a chain.
  Enabled: false
  Safe: false

Sevencop/MethodDefinitionArgumentsMultiline:
  Description: |
    Inserts new lines between method definition arguments.
  Enabled: false

Sevencop/MethodDefinitionInIncluded:
  Description: |
    Do not define methods in `included` blocks.
  Enabled: false
  Safe: false

Sevencop/MethodDefinitionOrdered:
  Description: |
    Sort method definitions in alphabetical order.
  Enabled: false
  Safe: false

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Description: |
    Sort method definition keyword arguments in alphabetical order.
  Enabled: false
  Safe: false

Sevencop/RailsBelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Enabled: false
  Safe: false

Sevencop/RailsDateAndTimeCalculation:
  Description: |
    Prefer ActiveSupport date and time helper.
  Enabled: false
  Safe: false

Sevencop/RailsOrderFieldArelSql:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Enabled: false
  Safe: false

Sevencop/RailsOrderFieldInOrderOf:
  Description: |
    Prefer `in_order_of` to MySQL `FIELD` function if possible.
  Enabled: false
  Safe: false

Sevencop/RailsRouteAs:
  Description: |
    Always use `as` option on routing methods.
  Enabled: false
  Include:
    - config/routes.rb

Sevencop/RailsRouteOrdered:
  Description: |
    Sort routes by path and HTTP method.
  Enabled: false
  Safe: false
  Include:
    - config/routes.rb

Sevencop/RailsSpecificActionName:
  Description: |
    Use only specific action names.
  Enabled: false
  ActionNames:
    - create
    - destroy
    - edit
    - index
    - new
    - show
    - update
  Include:
    - "**/app/controllers/**/*.rb"

Sevencop/RailsUniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false

Sevencop/RailsWhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Enabled: false
  Safe: false

Sevencop/RSpecDescribeHttpEndpoint:
  Description: |
    Pass HTTP endpoint identifier (e.g. `GET /users`) to top-level `describe` on request-specs.
  Enabled: false
  Include:
    - "**/spec/requests/**/*.rb"

Sevencop/RSpecEmptyLineAfterLet:
  Description: |
    Insert empty line after `let`.
  Enabled: false
  Include:
    - "**/spec/**/*.rb"

Sevencop/RSpecExamplesInSameGroup:
  Description: |
    Combine examples in the same groups in the time-consuming kinds of specs.
  Enabled: false
  IncludeSharedExamples: false
  Include:
    - "**/spec/controllers/**/*.rb"
    - "**/spec/requests/**/*.rb"

Sevencop/RSpecMatcherConsistentParentheses:
  Description: |
    Keep consistent parentheses style in RSpec matchers.
  Enabled: false
  Include:
    - "**/spec/**/*.rb"

Sevencop/RSpecMemoizedHelperBlockDelimiter:
  Description: |
    Use do-end block delimiter on RSpec memoized helper.
  Enabled: false
  Include:
    - "**/spec/**/*.rb"

Sevencop/RSpecRailsHaveHttpStatus:
  Description: |
    Always check status code with `have_http_status`.
  Enabled: false
  Include:
    - "**/spec/controllers/**/*.rb"
    - "**/spec/requests/**/*.rb"

Sevencop/RSpecRailsStatusCodeCheckBySubject:
  Description: |
    Use `expect(response).to have_http_status(code)` instead of `is_expected.to eq(code)`.
  Enabled: false
  Include:
    - "**/spec/controllers/**/*.rb"
    - "**/spec/requests/**/*.rb"
