Sevencop/AutoloadOrdered:
  Description: |
    Sort `autoload` in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.12'

Sevencop/ConstantBase:
  Description: |
    Avoid unnecessary `::` prefix on constant.
  Enabled: false
  VersionAdded: '0.31'

Sevencop/FactoryBotAssociationOption:
  Description: |
    Avoid redundant options on FactoryBot associations.
  Enabled: false
  VersionAdded: '0.21'

Sevencop/FactoryBotAssociationStyle:
  Description: |
    Use consistent style in FactoryBot associations.
  Enabled: false
  Safe: false
  VersionAdded: '0.21'
  EnforcedStyle: implicit
  SupportedStyles:
    - explicit
    - implicit
  inherit_mode:
    merge:
      - NonImplicitAssociationMethodNames
  NonImplicitAssociationMethodNames:
    - skip_create
  Include:
    - factories.rb
    - factories/*.rb
    - spec/factories.rb
    - spec/factories/*.rb
    - test/factories.rb
    - test/factories/*.rb

Sevencop/HashElementOrdered:
  Description: |
    Sort Hash elements by key.
  Enabled: false
  Safe: false
  VersionAdded: '0.6'

Sevencop/MethodDefinitionArgumentsMultiline:
  Description: |
    Inserts new lines between method definition arguments.
  Enabled: false
  VersionAdded: '0.11'

Sevencop/MethodDefinitionInIncluded:
  Description: |
    Do not define methods in `included` blocks.
  Enabled: false
  Safe: false
  VersionAdded: '0.19'

Sevencop/MethodDefinitionOrdered:
  Description: |
    Sort method definitions in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.14'

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Description: |
    Sort method definition keyword arguments in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.13'

Sevencop/RailsBelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Enabled: false
  Safe: false
  VersionAdded: '0.5'

Sevencop/RailsDateAndTimeCalculation:
  Description: |
    Prefer ActiveSupport date and time helper.
  Enabled: false
  Safe: false
  VersionAdded: '0.26'

Sevencop/RailsOrderField:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Enabled: false
  Safe: false
  VersionAdded: '0.4'

Sevencop/RailsOrderFieldInOrderOf:
  Description: |
    Prefer `in_order_of` to MySQL `FIELD` function.
  Enabled: false
  SafeAutoCorrect: false
  VersionAdded: '0.32'

Sevencop/RailsSpecificActionName:
  Description: |
    Use only specific action names.
  Enabled: false
  VersionAdded: '0.24'
  VersionChanged: '0.29'
  ActionNames:
    - create
    - destroy
    - edit
    - index
    - new
    - show
    - update
  Include:
    - app/controllers/**/*.rb

Sevencop/RailsUniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false
  VersionAdded: '0.3'

Sevencop/RailsWhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Enabled: false
  Safe: false
  VersionAdded: '0.7'

Sevencop/RequireOrdered:
  Description: |
    Sort `require` and `require_relative` in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.16'

Sevencop/RSpecDescribeHttpEndpoint:
  Description: |
    Pass HTTP endpoint identifier (e.g. `GET /users`) to top-level `describe` on request-specs.
  Enabled: false
  VersionAdded: '0.18'
  Include:
    - spec/requests/**/*.rb

Sevencop/RSpecEmptyLineAfterLet:
  Description: |
    Insert empty line after `let`.
  Enabled: false
  VersionAdded: '0.27'
  Include:
    - spec/**/*

Sevencop/RSpecExamplesInSameGroup:
  Description: |
    Combine examples in the same groups in the time-consuming kinds of specs.
  Enabled: false
  VersionAdded: '0.17'
  IncludeSharedExamples: false
  Include:
    - spec/controllers/**/*
    - spec/requests/**/*

Sevencop/RSpecMemoizedHelperBlockDelimiter:
  Description: |
    Use do-end block delimiter on RSpec memoized helper.
  Enabled: false
  VersionAdded: '0.27'
  Include:
    - spec/**/*

Sevencop/RSpecRailsResponseParsedBody:
  Description: |
    Prefer `response.parsed_body` to `JSON.parse(response.body)`.
  Enabled: false
  Safe: false
  VersionAdded: '0.28'
  Include:
    - spec/controllers/**/*
    - spec/requests/**/*
