Sevencop/RedundantExistenceCheck:
  Description: Avoid redundant existent check before file operation.
  Enabled: true
  Safe: false
  VersionAdded: '0.1'

Sevencop/UniquenessValidatorExplicitCaseSensitivity:
  Description: Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false
  VersionAdded: '0.3'
