Sevencop/AutoloadOrdered:
  Description: |
    Sort `autoload` in alphabetical order.
  Enabled: false
  VersionAdded: '0.12'

Sevencop/BelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Enabled: false
  Safe: false
  VersionAdded: '0.5'

Sevencop/HashLiteralOrder:
  Description: |
    Sort Hash literal entries by key.
  Enabled: false
  VersionAdded: '0.6'

Sevencop/InferredSpecType:
  Description: |
    Identifies redundant spec type.
  Enabled: false
  VersionAdded: '0.9'

Sevencop/MethodDefinitionKeywordArgumentsOrdered:
  Description: |
    Sort method definition keyword arguments in alphabetical order.
  Enabled: false
  VersionAdded: '0.13'

Sevencop/MethodDefinitionMultilineArguments:
  Description: |
    Inserts new lines between method definition parameters.
  Enabled: false
  VersionAdded: '0.11'

Sevencop/OrderField:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Enabled: false
  Safe: false
  VersionAdded: '0.4'

Sevencop/UniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false
  VersionAdded: '0.3'

Sevencop/WhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Enabled: false
  Safe: false
  VersionAdded: '0.7'
