Sevencop:
  Enabled: false

Sevencop/AutoloadOrdered:
  Description: |
    Sort `autoload` in alphabetical order.
  VersionAdded: '0.12'

Sevencop/HashElementOrdered:
  Description: |
    Sort Hash elements by key.
  VersionAdded: '0.6'

Sevencop/MethodDefinitionArgumentsMultiline:
  Description: |
    Inserts new lines between method definition arguments.
  VersionAdded: '0.11'

Sevencop/MethodDefinitionInIncluded:
  Description: |
    Do not define methods in `included` blocks.
  VersionAdded: '0.19'

Sevencop/MethodDefinitionOrdered:
  Description: |
    Sort method definitions in alphabetical order.
  VersionAdded: '0.14'

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Description: |
    Sort method definition keyword arguments in alphabetical order.
  VersionAdded: '0.13'

Sevencop/RailsBelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Safe: false
  VersionAdded: '0.5'

Sevencop/RailsInferredSpecType:
  Description: |
    Identifies redundant spec type.
  VersionAdded: '0.9'

Sevencop/RailsOrderField:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Safe: false
  VersionAdded: '0.4'

Sevencop/RailsUniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Safe: false
  VersionAdded: '0.3'

Sevencop/RailsWhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Safe: false
  VersionAdded: '0.7'

Sevencop/RequireOrdered:
  Description: |
    Sort `require` and `require_relative` in alphabetical order.
  VersionAdded: '0.16'

Sevencop/RSpecDescribeHttpEndpoint:
  Description: |
    Pass HTTP endpoint identifier to top-level `describe` on request-specs.
  VersionAdded: '0.18'
  Include:
    - spec/requests/**/*.rb

Sevencop/RSpecExamplesInSameGroup:
  Description: |
    Combine examples in the same groups in the time-consuming kinds of specs.
  VersionAdded: '0.17'
  Include:
    - spec/controllers/**/*
    - spec/requests/**/*
