Sevencop/BelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Enabled: false
  Safe: false
  VersionAdded: '0.5'

Sevencop/HashLiteralOrder:
  Description: |
    Sort Hash literal entries by key.
  Enabled: false
  VersionAdded: '0.6'

Sevencop/OrderField:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Enabled: false
  Safe: false
  VersionAdded: '0.4'

Sevencop/RedundantExistenceCheck:
  Description: |
    Avoid redundant existent check before file operation.
  Enabled: false
  Safe: false
  VersionAdded: '0.1'

Sevencop/UniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false
  VersionAdded: '0.3'

Sevencop/WhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Enabled: false
  Safe: false
  VersionAdded: '0.7'
