Sevencop/AutoloadOrdered:
  Description: |
    Sort `autoload` in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.12'

Sevencop/FactoryBotAssociationOptions:
  Description: |
    Remove redundant options from FactoryBot associations.
  Enabled: false
  VersionAdded: '0.21'

Sevencop/FactoryBotAssociationStyle:
  Description: |
    Use consistent style in FactoryBot associations.
  Enabled: false
  Safe: false
  VersionAdded: '0.21'
  EnforcedStyle: implicit
  SupportedStyles:
    - explicit
    - implicit
  inherit_mode:
    merge:
      - NonImplicitAssociationMethodNames
  NonImplicitAssociationMethodNames:
    - skip_create
  Include:
    - factories.rb
    - factories/*.rb
    - spec/factories.rb
    - spec/factories/*.rb
    - test/factories.rb
    - test/factories/*.rb

Sevencop/HashElementOrdered:
  Description: |
    Sort Hash elements by key.
  Enabled: false
  Safe: false
  VersionAdded: '0.6'

Sevencop/MethodDefinitionArgumentsMultiline:
  Description: |
    Inserts new lines between method definition arguments.
  Enabled: false
  VersionAdded: '0.11'

Sevencop/MethodDefinitionInIncluded:
  Description: |
    Do not define methods in `included` blocks.
  Enabled: false
  Safe: false
  VersionAdded: '0.19'

Sevencop/MethodDefinitionOrdered:
  Description: |
    Sort method definitions in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.14'

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Description: |
    Sort method definition keyword arguments in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.13'

Sevencop/RailsBelongsToOptional:
  Description: |
    Force `belongs_to` with `optional: true` option.
  Enabled: false
  Safe: false
  VersionAdded: '0.5'

Sevencop/RailsInferredSpecType:
  Description: |
    Identifies redundant spec type.
  Enabled: false
  Safe: false
  VersionAdded: '0.9'

Sevencop/RailsMigrationAddCheckConstraint:
  Description: |
    Activate a check constraint in a separate migration in PostgreSQL.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationAddColumnWithDefaultValue:
  Description: |
    Add the column without a default value then change the default.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationAddForeignKey:
  Description: |
    Activate a foreign key validation in a separate migration in PostgreSQL.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationAddIndexConcurrency:
  Description: |
    Use `algorithm: :concurrently` on adding indexes to existing tables in PostgreSQL.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationCreateTableForce:
  Description: |
    Create tables without `force: true` option.
  Enabled: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationJsonb:
  Description: |
    Prefer `jsonb` to `json`.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationChangeColumn:
  Description: |
    Avoid changing column type that is in use.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationChangeColumnNull:
  Description: |
    Avoid simply setting `NOT NULL` constraint on an existing column in PostgreSQL.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationRenameColumn:
  Description: |
    Avoid renaming columns that are in use.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationRenameTable:
  Description: |
    Avoid removing tables that are in use.
  Enabled: false
  Safe: false
  VersionAdded: '0.22'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationReservedWordMysql:
  Description: |
    Avoid using MySQL reserved words as identifiers.
  Enabled: false
  Safe: false
  VersionAdded: '0.20'
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsMigrationUniqueIndexColumnsCount:
  Description: |
    Keep unique index columns count less than a specified number.
  Enabled: false
  VersionAdded: '0.22'
  MaxColumnsCount: 3
  Include:
    - db/migrate/**/*.rb

Sevencop/RailsOrderField:
  Description: |
    Wrap safe SQL String by `Arel.sql`.
  Enabled: false
  Safe: false
  VersionAdded: '0.4'

Sevencop/RailsUniquenessValidatorExplicitCaseSensitivity:
  Description: |
    Specify :case_sensitivity option on use of UniquenessValidator.
  Enabled: false
  Safe: false
  VersionAdded: '0.3'

Sevencop/RailsWhereNot:
  Description: |
    Identifies passing multi-elements Hash literal to `where.not`.
  Enabled: false
  Safe: false
  VersionAdded: '0.7'

Sevencop/RequireOrdered:
  Description: |
    Sort `require` and `require_relative` in alphabetical order.
  Enabled: false
  Safe: false
  VersionAdded: '0.16'

Sevencop/RSpecDescribeHttpEndpoint:
  Description: |
    Pass HTTP endpoint identifier to top-level `describe` on request-specs.
  Enabled: false
  VersionAdded: '0.18'
  Include:
    - spec/requests/**/*.rb

Sevencop/RSpecExamplesInSameGroup:
  Description: |
    Combine examples in the same groups in the time-consuming kinds of specs.
  Enabled: false
  VersionAdded: '0.17'
  Include:
    - spec/controllers/**/*
    - spec/requests/**/*
