name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: default:rubocop
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3
      - run: bundle exec rubocop --format github --format progress
  rspec:
    name: rspec ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: default:test
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - run: bundle exec rspec
